// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOQmlmIfse2K7JRXKYKL7dBuLc_khgwt0',
    appId: '1:884108167778:web:21f682b66fb970dfde5f3b',
    messagingSenderId: '884108167778',
    projectId: 'aplikasi-pencatatan-b01e0',
    authDomain: 'aplikasi-pencatatan-b01e0.firebaseapp.com',
    databaseURL: 'https://aplikasi-pencatatan-b01e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-pencatatan-b01e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsDWYnNT5Lp1oKNXiLOiEKlUZuC07QEC4',
    appId: '1:884108167778:android:ccb45485831b2d54de5f3b',
    messagingSenderId: '884108167778',
    projectId: 'aplikasi-pencatatan-b01e0',
    databaseURL: 'https://aplikasi-pencatatan-b01e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-pencatatan-b01e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO1TEh4GfiAl_m-tHUEEcksxlEWJzkPBA',
    appId: '1:884108167778:ios:3ab4aa05ea8e8b3ede5f3b',
    messagingSenderId: '884108167778',
    projectId: 'aplikasi-pencatatan-b01e0',
    databaseURL: 'https://aplikasi-pencatatan-b01e0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-pencatatan-b01e0.firebasestorage.app',
    iosBundleId: 'com.example.projectPbiLuarsekolah',
  );
}
