// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VCaBuSj1FVkrPv9nVVwdFiZ787kLg7Y',
    appId: '1:178075470863:web:a8a8eefbb77df78246677a',
    messagingSenderId: '178075470863',
    projectId: 'note-app-af47b',
    authDomain: 'note-app-af47b.firebaseapp.com',
    databaseURL: 'https://note-app-af47b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-af47b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCECOdQaLEodil4oHpNwJGotjfsngz2y-k',
    appId: '1:178075470863:android:6c854a36ec9aa9d246677a',
    messagingSenderId: '178075470863',
    projectId: 'note-app-af47b',
    databaseURL: 'https://note-app-af47b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-af47b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEIK31P5q9Wg41A-t0kDm0cSHHRHwyICI',
    appId: '1:178075470863:ios:01bd5039702d60a046677a',
    messagingSenderId: '178075470863',
    projectId: 'note-app-af47b',
    databaseURL: 'https://note-app-af47b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'note-app-af47b.firebasestorage.app',
    iosBundleId: 'com.example.projectPbiLuarsekolah',
  );

}